---
- name: "查看是否有要发送的文件"
  stat: path="roles/call_webex/files/health_report.md"
  register: file_check

- name: "读取文件信息"
  debug: msg="{{lookup('file', 'health_report.md') }}"
  register:   health_tenant_message
  when: file_check.stat.exists
  
- name: "通过Webex Teams发送信息" 
  cisco_spark:
    recipient_type:   roomId
    recipient_id:     "{{ roomID }}"
    message_type:     markdown
    personal_token:   "{{ bot_token }}"
    message:          "{{ health_tenant_message.msg }}"
  when: file_check.stat.exists

- name: "删除数据文件"
  file:
    path: roles/call_webex/files/health_report.md
    state: absent
